CREATE TABLE comments(

id BIGINT AUTO_INCREMENT PRIMARY KEY,
message TEXT NOT NULL,
topic_id BIGINT NOT NULL,
user_id BIGINT NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (topic_id) REFERENCES topics(id),
status BOOLEAN NOT NULL DEFAULT TRUE

)